// swift-tools-version: 5.9
import PackageDescription

// Generated by cardlink-sdk/scripts/release-packages.sh — do not edit by hand.
// One public Swift Package hosting every Scoop SDK XCFramework (sources stay private).
let package = Package(
    name: "CardlinkPackages",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "ScoopCardlink", targets: ["ScoopCardlink"]),
        .library(name: "ScoopNfc", targets: ["ScoopNfc"]),
        .library(name: "ScoopNfcUI", targets: ["ScoopNfcUI"]),
        .library(name: "ScoopPopp", targets: ["ScoopPopp"]),
    ],
    targets: [
        .binaryTarget(
            name: "ScoopCardlink",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.6.0/ScoopCardlink.xcframework.zip",
            checksum: "8635de0515d55e680adc1ed99e766d7f758ebd69e0e27c7dd6a9026c3c03da46"
        ),
        .binaryTarget(
            name: "ScoopNfc",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.6.0/ScoopNfc.xcframework.zip",
            checksum: "c992ad906160e6bd9e963e6a8f4536f3a92a3d751fb206063a802fee3bcd181e"
        ),
        .binaryTarget(
            name: "ScoopNfcUI",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.6.0/ScoopNfcUI.xcframework.zip",
            checksum: "07775dacce9bd4d85766919bbf6750f13a3fb82615bcdf42d8bd71f794693826"
        ),
        .binaryTarget(
            name: "ScoopPopp",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.6.0/ScoopPopp.xcframework.zip",
            checksum: "6e2078855d155c3c327174ca6e1e111de1ae33f2147c031c96c1be6e346fc87d"
        ),
    ]
)
