// swift-tools-version: 5.9
import PackageDescription

// Generated by cardlink-sdk/scripts/release-packages.sh — do not edit by hand.
// One public Swift Package hosting every Scoop SDK XCFramework (sources stay private).
let package = Package(
    name: "CardlinkPackages",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "ScoopCardlink", targets: ["ScoopCardlink"]),
        .library(name: "ScoopNfc", targets: ["ScoopNfc"]),
        .library(name: "ScoopNfcUI", targets: ["ScoopNfcUI"]),
        .library(name: "ScoopPopp", targets: ["ScoopPopp"]),
    ],
    targets: [
        .binaryTarget(
            name: "ScoopCardlink",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.3.0/ScoopCardlink.xcframework.zip",
            checksum: "c9872db746ef827644186aedd8bb783ffaf1878be3b11552b6a75e06a317e161"
        ),
        .binaryTarget(
            name: "ScoopNfc",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.3.0/ScoopNfc.xcframework.zip",
            checksum: "74672f823949efc347ed0cc4f1bc56e8c8e8305c3a76721ee11fa17756103432"
        ),
        .binaryTarget(
            name: "ScoopNfcUI",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.3.0/ScoopNfcUI.xcframework.zip",
            checksum: "a6877bf2ad97b3345dff60a9917f31c7c1539a70d6c66f35857b87025386eeca"
        ),
        .binaryTarget(
            name: "ScoopPopp",
            url: "https://github.com/scoop-software/cardlink-packages/releases/download/v2.3.0/ScoopPopp.xcframework.zip",
            checksum: "8532919c565d607364faf59d7693c8acd5cf5d2bd33d2dd914ce0c1c083dc1e0"
        ),
    ]
)
