// swift-tools-version: 5.9
// Generated by cardlink-sdk/scripts/release-packages.sh — do not edit by hand.
// Legacy public manifest retained so existing consumers can keep their assigned pins.
// It is not the active distribution route for new Evaluation/Pilot integrations.
import PackageDescription

let package = Package(
    name: "cardlink-packages",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ScoopCardlink", targets: ["ScoopCardlink"]),
        .library(name: "ScoopNfc", targets: ["ScoopNfc"]),
        .library(name: "ScoopNfcUI", targets: ["ScoopNfcUI", "ScoopNfc"]),
        .library(name: "ScoopPopp", targets: ["ScoopPopp"]),
    ],
    targets: [
        .binaryTarget(name: "ScoopCardlink", url: "https://github.com/scoop-software/cardlink-packages/releases/download/v4.0.0/ScoopCardlink.xcframework.zip", checksum: "1d8fe6a5ade569bdab8515d028362a54b09b4731863d0470959d840736ba07de"),
        .binaryTarget(name: "ScoopNfc", url: "https://github.com/scoop-software/cardlink-packages/releases/download/v4.0.0/ScoopNfc.xcframework.zip", checksum: "c250ee87f1df34135b178a9d038e551882c1476891e206931beeae08aaf7c669"),
        .binaryTarget(name: "ScoopNfcUI", url: "https://github.com/scoop-software/cardlink-packages/releases/download/v4.0.0/ScoopNfcUI.xcframework.zip", checksum: "3f711bf3e286e863e1ca48d7e76da7466f4e901e7fba3952d1b65b9a9e71e9b8"),
        .binaryTarget(name: "ScoopPopp", url: "https://github.com/scoop-software/cardlink-packages/releases/download/v4.0.0/ScoopPopp.xcframework.zip", checksum: "02dcb07236d94e26ea8baa12dae8983a216c106fece2a20e83125903d5601382"),
    ]
)
